# Generated by Django 4.0.3 on 2022-03-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('size', models.CharField(choices=[('adult', 'ADULT'), ('child', 'CHILD')], max_length=5)),
            ],
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='ElectricScooter',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('range', models.IntegerField()),
            ],
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('range', models.IntegerField()),
                ('registration', models.CharField(default='0000AAA', max_length=7, unique=True)),
            ],
            bases=('main.transport',),
        ),
    ]
