# Generated by Django 4.0.3 on 2022-05-09 10:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('size', models.CharField(choices=[('adult', 'ADULT'), ('child', 'CHILD')], max_length=5)),
            ],
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='ElectricScooter',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('range', models.IntegerField()),
            ],
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('range', models.IntegerField()),
            ],
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('start_point', models.CharField(choices=[('green street', 'GREEN STREET'), ('blue street', 'BLUE STREET'), ('red street', 'RED STREET'), ('yellow street', 'YELLOW STREET'), ('brown street', 'BROWN STREET'), ('black street', 'BLACK STREET')], max_length=20)),
                ('end_point', models.CharField(choices=[('green street', 'GREEN STREET'), ('blue street', 'BLUE STREET'), ('red street', 'RED STREET'), ('yellow street', 'YELLOW STREET'), ('brown street', 'BROWN STREET'), ('black street', 'BLACK STREET')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('km', models.IntegerField()),
                ('id_vehicle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.myuser')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='vehicle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.transport'),
        ),
    ]
