# Generated by Django 4.0.3 on 2022-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_route_end_point_alter_route_start_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_point',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_point',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
